@host = http://localhost:3030/api/users
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcwMTk0NzkyOSwiZXhwIjoxNzAxOTkxMTI5fQ.eJtYSoFcKDKR-YuoVP66YpZiZJD4fNDNmjkEdNtsupo

### 내 정보 조회
GET {{host}}/me
Authorization: Bearer {{accessToken}}